steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'website_feature_finder'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/webglazer-prototype/webglazer-prototype:$SHORT_SHA', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/webglazer-prototype/webglazer-prototype:$SHORT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'webglazer-prototype'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/webglazer-prototype/webglazer-prototype:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'DEBUG=0'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/webglazer-prototype/webglazer-prototype:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'

