# Generated by Django 5.2.10 on 2026-01-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('ai_pages', models.JSONField(blank=True, default=list)),
                ('findability_report', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
